name: Lint
on:
  pull_request:
  push:
    branches: [main]
jobs:
  eslint:
    name: Lint / eslint
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20.19.4
#npmで実行する場合は以下を有効化
          cache: npm
          cache-dependency-path: package-lock.json
      - run: npm ci
      - run: npx eslint . --format json
#以下はnpmとyarnの両方で有効化
      - uses: ataylorme/eslint-annotate-action@v3
        if: always()
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          report-json: eslint-report.json
